package com.example.employee_sytem.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * Entity class representing an employee in the system.
 * <p>
 * This class is mapped to the "employees" table in the database and defines the attributes
 * associated with an employee.
 * </p>
 */
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Entity
@Table(name= "employees")
@Data
public class Employee {

    /**
     * The unique identifier for the employee.
     * This field is automatically generated by the database.
     */

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * The first name of the employee.
     */
    @Column(name= "first_name")
    private String firstName;
    /**
     * The last name of the employee.
     */
    @Column(name="last_name")
    private String lastName;
    /**
     * The email address of the employee.
     * This field must be unique and cannot be null.
     */
    @Column(name="email_id",nullable = false,unique = true)
    private String email;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id")
    private Department department;
    @Column(nullable = false)
    private boolean active=false;
    public Employee(Long id, String firstName, String lastName, String email) {
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }


    // Convenience method to get the full name of the employee
    public String getFullName() {
        return firstName + " " + lastName;
    }

    @ManyToOne
    @JoinColumn(name = "manager_id") // The foreign key in the employees table
    private Employee manager; // Assuming Employee can be a manager of other Employees


}